### ISSUE TITLE
Human annotations comparing model generated text with references

### ISSUE THREAD

**Issue by martiansideofthemoon** [nyu-mll/SQuALITY#1]
Hi @W4ngatang, thanks for the great work and repository, super interesting!

Could you also share your human annotations comparing model generated outputs and reference summaries? Any format is fine, doesn't need to be super clean.

Thank you,
Kalpesh

**Comment by W4ngatang** [comment]
Hi @martiansideofthemoon ,

The data is now available here: https://github.com/nyu-mll/SQuALITY/tree/main/data/human-eval
I wasn't entirely sure what the best format would be for the data, so if you have thoughts about how to format the data to be more usable or any additional fields you might be interested in, just let me know.

Best,
Alex
